export const musicGenres: { name: string; parent?: string }[] = [
  { name: "Andalusian classical music" },
  { name: "Indian classical music" },
  { name: "Korean court music" },
  { name: "Persian classical music" },
  { name: "Western classical music" },
  { name: "Early Western Classical Music", parent: "Western classical music" },
  { name: "Medieval music", parent: "Western classical music" },
  { name: "Ars antiqua", parent: "Medieval music" },
  { name: "Ars nova", parent: "Medieval music" },
  { name: "Ars subtilior", parent: "Medieval music" },
  { name: "Renaissance music", parent: "Western classical music" },
  { name: "Baroque music", parent: "Western classical music" },
  { name: "Galant music", parent: "Western classical music" },
  { name: "Classical period", parent: "Western classical music" },
  { name: "Romantic music", parent: "Western classical music" },
  { name: "Modernism", parent: "Western classical music" },
  { name: "Impressionism", parent: "Western classical music" },
  { name: "Neoclassicism", parent: "Western classical music" },
  { name: "High modernism", parent: "Western classical music" },
  { name: "Postmodern music", parent: "Western classical music" },
  { name: "Experimental music", parent: "Western classical music" },
  { name: "Contemporary classical music", parent: "Western classical music" },
  { name: "Minimal music", parent: "Western classical music" },
  { name: "Crossover music" },
  { name: "Danger music" },
  { name: "Drone music" },
  { name: "Electroacoustic" },
  { name: "Industrial music" },
  { name: "Instrumental" },
  { name: "Lo-fi" },
  { name: "Musical improvisation" },
  { name: "Musique concrète" },
  { name: "Noise" },
  { name: "Outsider music" },
  { name: "Progressive music" },
  { name: "Psychedelic music" },
  { name: "Blues" },
  { name: "African blues", parent: "Blues" },
  { name: "Blues rock", parent: "Blues" },
  { name: "Blues shouter", parent: "Blues" },
  { name: "British blues", parent: "Blues" },
  { name: "Canadian blues", parent: "Blues" },
  { name: "Chicago blues", parent: "Blues" },
  { name: "Classic female blues", parent: "Blues" },
  { name: "Contemporary R&B", parent: "Blues" },
  { name: "Country blues", parent: "Blues" },
  { name: "Delta blues", parent: "Blues" },
  { name: "Desert blues", parent: "Blues" },
  { name: "Detroit blues", parent: "Blues" },
  { name: "Electric blues", parent: "Blues" },
  { name: "Gospel blues", parent: "Blues" },
  { name: "Hill country blues", parent: "Blues" },
  { name: "Hokum blues", parent: "Blues" },
  { name: "Honky Tonk Blues", parent: "Blues" },
  { name: "Jump blues", parent: "Blues" },
  { name: "Kansas City blues", parent: "Blues" },
  { name: "Louisiana blues", parent: "Blues" },
  { name: "Memphis blues", parent: "Blues" },
  { name: "New Orleans blues", parent: "Blues" },
  { name: "Piedmont blues", parent: "Blues" },
  { name: "Punk blues", parent: "Blues" },
  { name: "Rhythm and blues", parent: "Blues" },
  { name: "Doo-wop", parent: "Rhythm and blues" },
  { name: "Soul blues", parent: "Blues" },
  { name: "St. Louis blues", parent: "Blues" },
  { name: "Swamp blues", parent: "Blues" },
  { name: "Talking blues", parent: "Blues" },
  { name: "Texas blues", parent: "Blues" },
  { name: "West Coast blues", parent: "Blues" },
  { name: "Country" },
  { name: "Alternative country", parent: "Country" },
  { name: "Americana", parent: "Country" },
  { name: "Cowpunk", parent: "Country" },
  { name: "Gothic country", parent: "Country" },
  { name: "Roots rock", parent: "Country" },
  { name: "Australian country", parent: "Country" },
  { name: "Bush band", parent: "Australian country" },
  { name: "Bakersfield sound", parent: "Country" },
  { name: "Bluegrass", parent: "Country" },
  { name: "Old-time bluegrass", parent: "Bluegrass" },
  { name: "Appalachian bluegrass", parent: "Old-time bluegrass" },
  { name: "Traditional bluegrass", parent: "Bluegrass" },
  { name: "Neo-traditional bluegrass", parent: "Traditional bluegrass" },
  { name: "Progressive bluegrass", parent: "Bluegrass" },
  { name: "Nu-grass", parent: "Progressive bluegrass" },
  { name: "Bluegrass gospel", parent: "Bluegrass" },
  { name: "Blue Yodeling", parent: "Country" },
  { name: "Bro-country", parent: "Country" },
  { name: "Cajun", parent: "Country" },
  { name: "Cajun fiddle", parent: "Cajun" },
  { name: "Canadian country", parent: "Country" },
  { name: "Franco-country", parent: "Canadian country" },
  { name: "Christian country", parent: "Country" },
  { name: "Classic country", parent: "Country" },
  { name: "Country and Irish", parent: "Country" },
  { name: "Country blues", parent: "Country" },
  { name: "Country en Español", parent: "Country" },
  { name: "Country folk", parent: "Country" },
  { name: "Country pop", parent: "Country" },
  { name: "Cosmopolitan country", parent: "Country pop" },
  { name: "Country rap", parent: "Country" },
  { name: "Hick-hop", parent: "Country rap" },
  { name: "Country rock", parent: "Country" },
  { name: "Cowboy pop", parent: "Country" },
  { name: "Dansband", parent: "Country" },
  { name: "Gulf and Western", parent: "Country" },
  { name: "Hokum", parent: "Country" },
  { name: "Honky tonk", parent: "Country" },
  { name: "Instrumental country", parent: "Country" },
  { name: "Lubbock sound", parent: "Country" },
  { name: "Nashville sound", parent: "Country" },
  { name: "Countrypolitan", parent: "Nashville sound" },
  { name: "Neotraditional country", parent: "Country" },
  { name: "New country", parent: "Neotraditional country" },
  { name: "Old-time", parent: "Country" },
  { name: "Outlaw country", parent: "Country" },
  { name: "Pop country", parent: "Country" },
  { name: "Progressive country", parent: "Country" },
  { name: "Regional Mexican", parent: "Country" },
  { name: "Rockabilly", parent: "Country" },
  { name: "Neo-Rockabilly", parent: "Rockabilly" },
  { name: "Psychobilly", parent: "Neo-Rockabilly" },
  { name: "Punkabilly", parent: "Psychobilly" },
  { name: "Gothabilly", parent: "Psychobilly" },
  { name: "Hellbilly", parent: "Gothabilly" },
  { name: "Southern rock", parent: "Country" },
  { name: "Southern soul", parent: "Country" },
  { name: "Sertanejo", parent: "Country" },
  { name: "Talking blues", parent: "Country" },
  { name: "Traditional country", parent: "Country" },
  { name: "Truck-driving country", parent: "Country" },
  { name: "Western music", parent: "Country" },
  { name: "Western/cowboy music", parent: "Country" },
  { name: "New Mexico music", parent: "Western/cowboy music" },
  { name: "Red dirt", parent: "Western/cowboy music" },
  { name: "Tejano/Tex-Mex", parent: "Western/cowboy music" },
  { name: "Texas country", parent: "Western/cowboy music" },
  { name: "Western swing", parent: "Western/cowboy music" },
  { name: "Zydeco", parent: "Western/cowboy music" },
  { name: "Easy listening" },
  { name: "Adult contemporary music", parent: "Easy listening" },
  { name: "Adult standards", parent: "Easy listening" },
  { name: "Background music", parent: "Easy listening" },
  { name: "Elevator music (muzak)", parent: "Easy listening" },
  { name: "Barococo", parent: "Easy listening" },
  { name: "Beautiful music", parent: "Easy listening" },
  { name: "Chill-out", parent: "Easy listening" },
  { name: "Downtempo", parent: "Easy listening" },
  { name: "Furniture music", parent: "Easy listening" },
  { name: "Light music", parent: "Easy listening" },
  { name: "Lounge music", parent: "Easy listening" },
  { name: "Middle of the road", parent: "Easy listening" },
  { name: "New-age music", parent: "Easy listening" },
  { name: "Soft rock", parent: "Easy listening" },
  { name: "Electronic" },
  { name: "Ambient", parent: "Electronic" },
  { name: "Ambient dub", parent: "Ambient" },
  { name: "Dark ambient", parent: "Ambient" },
  { name: "Ambient industrial", parent: "Ambient" },
  { name: "Dungeon synth", parent: "Ambient" },
  { name: "Isolationism", parent: "Ambient" },
  { name: "Dreampunk", parent: "Ambient" },
  { name: "Illbient", parent: "Ambient" },
  { name: "Neoclassical new-age", parent: "New-age music" },
  { name: "Space music", parent: "Ambient" },
  { name: "Bass music", parent: "Electronic" },
  { name: "Footwork", parent: "Bass music" },
  { name: "Future bass", parent: "Bass music" },
  { name: "Kawaii future bass", parent: "Future bass" },
  { name: "Jungle terror", parent: "Bass music" },
  { name: "Midtempo bass", parent: "Bass music" },
  { name: "Trap (EDM)", parent: "Bass music" },
  { name: "UK bass", parent: "Bass music" },
  { name: "Wave", parent: "Bass music" },
  { name: "Hardwave", parent: "Wave" },
  { name: "Breakbeat", parent: "Electronic" },
  { name: "Acid breaks", parent: "Breakbeat" },
  { name: "Baltimore club", parent: "Breakbeat" },
  { name: "Jersey club", parent: "Breakbeat" },
  { name: "Philly club", parent: "Breakbeat" },
  { name: "Big beat", parent: "Breakbeat" },
  { name: "Breakbeat hardcore", parent: "Breakbeat" },
  { name: "Darkcore", parent: "Breakbeat" },
  { name: "Hardcore breaks", parent: "Breakbeat" },
  { name: "Broken beat", parent: "Breakbeat" },
  { name: "Florida breaks", parent: "Breakbeat" },
  { name: "Nu skool breaks", parent: "Breakbeat" },
  { name: "Progressive breaks", parent: "Breakbeat" },
  { name: "Psychedelic breakbeat", parent: "Breakbeat" },
  { name: "Psybient", parent: "Chill-out" },
  { name: "Psydub", parent: "Chill-out" },
  { name: "Trip hop", parent: "Chill-out" },
  { name: "Trip rock", parent: "Trip hop" },
  { name: "Disco", parent: "Electronic" },
  { name: "Afro/cosmic music", parent: "Disco" },
  { name: "Electro-disco", parent: "Disco" },
  { name: "Hi-NRG", parent: "Disco" },
  { name: "Eurobeat", parent: "Disco" },
  { name: "Eurodance", parent: "Disco" },
  { name: "Italo dance", parent: "Disco" },
  { name: "Italo disco", parent: "Disco" },
  { name: "Spacesynth", parent: "Disco" },
  { name: "Space disco", parent: "Disco" },
  { name: "Eurodisco", parent: "Disco" },
  { name: "Nu-disco", parent: "Disco" },
  { name: "Post-disco", parent: "Disco" },
  { name: "Boogie", parent: "Disco" },
  { name: "City pop", parent: "Disco" },
  { name: "Drum and bass", parent: "Electronic" },
  { name: "Darkstep", parent: "Drum and bass" },
  { name: "Drumfunk", parent: "Drum and bass" },
  { name: "Drumstep", parent: "Drum and bass" },
  { name: "Hardstep", parent: "Drum and bass" },
  { name: "Intelligent drum and bass", parent: "Drum and bass" },
  { name: "Atmospheric drum and bass", parent: "Drum and bass" },
  { name: "Jazzstep", parent: "Drum and bass" },
  { name: "Jump-up", parent: "Drum and bass" },
  { name: "Liquid funk", parent: "Drum and bass" },
  { name: "Neurofunk", parent: "Drum and bass" },
  { name: "Sambass", parent: "Drum and bass" },
  { name: "Techstep", parent: "Drum and bass" },
  { name: "Dub", parent: "Electronic" },
  { name: "Dub poetry", parent: "Dub" },
  { name: "Dubtronica", parent: "Dub" },
  { name: "Electronic rock", parent: "Electronic" },
  { name: "Dance-rock", parent: "Electronic rock" },
  { name: "Alternative dance", parent: "Electronic rock" },
  { name: "Baggy (Madchester)", parent: "Alternative dance" },
  { name: "New rave", parent: "Alternative dance" },
  { name: "Dance-punk", parent: "Alternative dance" },
  { name: "Electronic pop", parent: "Electronic" },
  { name: "Dance-pop", parent: "Electronic pop" },
  { name: "Freestyle", parent: "Dance-pop" },
  { name: "Disco polo", parent: "Dance-pop" },
  { name: "Hyperpop", parent: "Dance-pop" },
  { name: "Sophisti-pop", parent: "Dance-pop" },
  { name: "Synth-pop", parent: "Dance-pop" },
  { name: "Electroclash", parent: "Synth-pop" },
  { name: "Electropop", parent: "Synth-pop" },
  { name: "Wonky pop", parent: "Dance-pop" },
  { name: "Indietronica", parent: "Electronic" },
  { name: "Krautrock", parent: "Electronic" },
  { name: "New wave", parent: "Electronic" },
  { name: "Cold wave", parent: "New wave" },
  { name: "Dark wave", parent: "New wave" },
  { name: "Neoclassical dark wave", parent: "Dark wave" },
  { name: "Neue Deutsche Todeskunst", parent: "Dark wave" },
  { name: "Ethereal wave", parent: "Dark wave" },
  { name: "Nu-gaze", parent: "Ethereal wave" },
  { name: "Minimal wave", parent: "New wave" },
  { name: "Neue Deutsche Welle", parent: "New wave" },
  { name: "New romantic", parent: "New wave" },
  { name: "Post-rock", parent: "Electronic" },
  { name: "Space rock", parent: "Post-rock" },
  { name: "Synth-metal", parent: "Electronic" },
  { name: "Electrogrind", parent: "Synth-metal" },
  { name: "Electronicore", parent: "Electronic" },
  { name: "Synth-punk", parent: "Electronic" },
  { name: "Folk punk", parent: "Punk" },
  { name: "Celtic punk", parent: "Punk" },
  { name: "Cowpunk", parent: "Punk" },
  { name: "Gypsy punk", parent: "Punk" },
  { name: "Scottish Gaelic punk", parent: "Punk" },
  { name: "Garage punk", parent: "Punk" },
  { name: "German punk", parent: "Punk" },
  { name: "Glam punk", parent: "Punk" },
  { name: "Gothic punk", parent: "Punk" },
  { name: "Grindcore", parent: "Punk" },
  { name: "Crustgrind", parent: "Grindcore" },
  { name: "Electrogrind", parent: "Grindcore" },
  { name: "Goregrind", parent: "Grindcore" },
  { name: "Noisegrind", parent: "Grindcore" },
  { name: "Pornogrind", parent: "Grindcore" },
  { name: "Hardcore punk", parent: "Punk" },
  { name: "Bardcore", parent: "Hardcore punk" },
  { name: "Beatdown hardcore", parent: "Hardcore punk" },
  { name: "Christian hardcore", parent: "Hardcore punk" },
  { name: "Crabcore", parent: "Hardcore punk" },
  { name: "Crunkcore", parent: "Hardcore punk" },
  { name: "Electronicore", parent: "Hardcore punk" },
  { name: "Krishnacore", parent: "Hardcore punk" },
  { name: "Melodic hardcore", parent: "Hardcore punk" },
  { name: "Positive hardcore", parent: "Hardcore punk" },
  { name: "Post-hardcore", parent: "Hardcore punk" },
  { name: "Queercore", parent: "Hardcore punk" },
  { name: "Taqwacore", parent: "Hardcore punk" },
  { name: "Emo", parent: "Punk" },
  { name: "Emo pop", parent: "Emo" },
  { name: "Screamo", parent: "Emo" },
  { name: "Powerviolence", parent: "Hardcore punk" },
  { name: "Street punk", parent: "Punk" },
  { name: "Horror punk", parent: "Punk" },
  { name: "Latino punk", parent: "Punk" },
  { name: "Oi!", parent: "Punk" },
  { name: "Pop punk", parent: "Punk" },
  { name: "Easycore", parent: "Pop punk" },
  { name: "Neon pop", parent: "Pop punk" },
  { name: "Post-punk", parent: "Punk" },
  { name: "Dance-punk", parent: "Post-punk" },
  { name: "Post-punk revival", parent: "Post-punk" },
  { name: "Proto-punk", parent: "Punk" },
  { name: "Psychobilly", parent: "Punk" },
  { name: "Punkabilly", parent: "Punk" },
  { name: "Punk blues", parent: "Punk" },
  { name: "Punk jazz", parent: "Punk" },
  { name: "Punk pathetique", parent: "Punk" },
  { name: "Punk rap", parent: "Punk" },
  { name: "Reggae punk", parent: "Punk" },
  { name: "Riot grrrl", parent: "Punk" },
  { name: "Ska punk", parent: "Punk" },
  { name: "Skate punk", parent: "Punk" },
  { name: "Street punk", parent: "Punk" },
  { name: "Surf punk", parent: "Punk" },
  { name: "Trallpunk", parent: "Punk" },
  { name: "African heavy metal" },
  { name: "African hip hop" },
  { name: "Afro pop" },
  { name: "Afrobeat" },
  { name: "Afrobeats" },
  { name: "Afro house" },
  { name: "Amapiano" },
  { name: "Apala" },
  { name: "Arabesque" },
  { name: "Afro tech" },
  { name: "Benga" },
  { name: "Bikutsi" },
  { name: "Bongo flava" },
  { name: "Boomba" },
  { name: "Bubu music" },
  { name: "Cape jazz" },
  { name: "Chaabi" },
  { name: "Chalga" },
  { name: "Chaoui music" },
  { name: "Chimurenga" },
  { name: "Congolese rumba" },
  { name: "Coupé-Décalé" },
  { name: "Fuji music" },
  { name: "Genge" },
  { name: "Gnawa" },
  { name: "Gqom" },
  { name: "Gumbe" },
  { name: "Highlife" },
  { name: "Hiplife" },
  { name: "Igbo highlife" },
  { name: "Igbo rap" },
  { name: "Ikorodo" },
  { name: "Ikwokirikwo" },
  { name: "Isicathamiya" },
  { name: "Jit" },
  { name: "Jùjú" },
  { name: "Kadongo Kamu" },
  { name: "Kizomba" },
  { name: "Kuduro" },
  { name: "Kwaito" },
  { name: "Kwela" },
  { name: "Lingala" },
  { name: "Makossa" },
  { name: "Maloya" },
  { name: "Ma'luf" },
  { name: "Marabi" },
  { name: "Marrabenta" },
  { name: "Mbalax" },
  { name: "Mbaqanga" },
  { name: "Mbube" },
  { name: "Morna" },
  { name: "Ndombolo" },
  { name: "Owerri Bongo" },
  { name: "Ojapiano" },
  { name: "Palm-wine" },
  { name: "Raï" },
  { name: "Rumba" },
  { name: "Sakara" },
  { name: "Sega" },
  { name: "Seggae" },
  { name: "Semba" },
  { name: "Shangaan electro" },
  { name: "Soukous" },
  { name: "Kwassa kwassa", parent: "Soukous" },
  { name: "Taarab" },
  { name: "Zamrock" },
  { name: "Zouglou" },
  { name: "Shashmaqam" },
  { name: "Pashto music" },
  { name: "Kazakh folk music" },
  { name: "Kyrgyz folk music" },
  { name: "Mongolian folk music" },
  { name: "Tuvan throat singing" },
  { name: "Tajik folk music" },
  { name: "C-pop" },
  { name: "Cantopop" },
  { name: "Hokkien pop" },
  { name: "Mandopop" },
  { name: "Chinese hip hop" },
  { name: "Chinese folk music" },
  { name: "Chinese rock" },
  { name: "Hong Kong English pop" },
  { name: "Hong Kong hip hop" },
  { name: "Taiwanese hip hop" },
  { name: "Taiwanese pop" },
  { name: "Taiwanese rock" },
  { name: "Anime song" },
  { name: "Enka" },
  { name: "J-pop" },
  { name: "Japanese hip hop" },
  { name: "Japanese jazz" },
  { name: "Japanese rock" },
  { name: "Kayōkyoku" },
  { name: "K-pop" },
  { name: "Korean folk music" },
  { name: "Korean hip hop" },
  { name: "Korean rock" },
  { name: "Trot" },
  { name: "Asian Underground" },
  { name: "Baul" },
  { name: "Bhangra" },
  { name: "Bhawaiya" },
  { name: "Dohori" },
  { name: "Filmi" },
  { name: "Indian classical" },
  { name: "Carnatic" },
  { name: "Hindustani classical" },
  { name: "Indian jazz" },
  { name: "Indian pop" },
  { name: "Indian rock" },
  { name: "Raga rock" },
  { name: "Kuthu" },
  { name: "Lavani" },
  { name: "Morlam" },
  { name: "Ragini" },
  { name: "Sufi rock" },
  { name: "Baila" },
  { name: "Sri Lankan hip hop" },
  { name: "Malaysian hip hop" },
  { name: "Malaysian pop" },
  { name: "Malaysian rock" },
  { name: "Gamelan" },
  { name: "Dangdut" },
  { name: "Indo pop" },
  { name: "Sundanese pop" },
  { name: "Keroncong" },
  { name: "Luk thung" },
  { name: "Luk krung" },
  { name: "Thai pop" },
  { name: "Thai string pop" },
  { name: "Manila sound" },
  { name: "Original Pilipino" },
  { name: "Pinoy pop" },
  { name: "Pinoy rock" },
  { name: "L-pop" },
  { name: "Mor lam" },
  { name: "V-pop" },
  { name: "Arabic music" },
  { name: "Arabic pop music" },
  { name: "Fann at-Tanbura" },
  { name: "Fijiri" },
  { name: "Khaliji" },
  { name: "Liwa" },
  { name: "Persian traditional music" },
  { name: "Sawt" },
  { name: "Turkish folk music" },
  { name: "Gypsy music" },
  { name: "Australian folk music" },
  { name: "Australian hip hop" },
  { name: "Indigenous music of Australia" },
  { name: "Māori music" },
  { name: "Kapa haka" },
  { name: "Balkan music" },
  { name: "Balkan brass" },
  { name: "Balkan folk music" },
  { name: "Romani music" },
  { name: "Gypsy music" },
  { name: "Lithuanian folk music" },
  { name: "Shashmaqam" },
  { name: "Pashto music" },
  { name: "Kazakh folk music" },
  { name: "Kyrgyz folk music" },
  { name: "Mongolian folk music" },
  { name: "Tuvan throat singing" },
  { name: "Tajik folk music" },
  { name: "Nordic folk music" },
  { name: "Danish traditional music" },
  { name: "Yodeling" },
  { name: "Klezmer" },
  { name: "Russian folk music" },
  { name: "Celtic music" },
  { name: "Axé" },
  { name: "Brazilian rock" },
  { name: "Brega" },
  { name: "Tecnobrega" },
  { name: "Choro" },
  { name: "Forró" },
  { name: "Frevo" },
  { name: "Funk carioca" },
  { name: "Lambada" },
  { name: "Zouk-Lambada" },
  { name: "Maracatu" },
  { name: "Música popular brasileira" },
  { name: "Tropicalia" },
  { name: "Música sertaneja" },
  { name: "Samba" },
  { name: "Pagode" },
  { name: "Samba rock" },
  { name: "Baithak Gana" },
  { name: "Bouyon" },
  { name: "Cadence-lypso" },
  { name: "Calypso" },
  { name: "Cha-cha-chá" },
  { name: "Chutney" },
  { name: "Chutney soca" },
  { name: "Chutney parang" },
  { name: "Compas" },
  { name: "Dancehall" },
  { name: "Mambo" },
  { name: "Mento" },
  { name: "Merengue" },
  { name: "Méringue" },
  { name: "Mozambique" },
  { name: "Pichakaree" },
  { name: "Punta" },
  { name: "Punta rock" },
  { name: "Rasin" },
  { name: "Reggae" },
  { name: "Dub" },
  { name: "Lovers rock" },
  { name: "Ragga" },
  { name: "Reggae fusion" },
  { name: "Ragga jungle" },
  { name: "Reggae rock" },
  { name: "Reggaeton" },
  { name: "Moombahton" },
  { name: "Roots reggae" },
  { name: "Rocksteady" },
  { name: "Rumba" },
  { name: "Salsa" },
  { name: "Ska" },
  { name: "Ska punk" },
  { name: "Two-tone" },
  { name: "Soca" },
  { name: "Power soca" },
  { name: "Son cubano" },
  { name: "Songo" },
  { name: "Timba" },
  { name: "Twoubadou" },
  { name: "Zouk" },
  { name: "Boogaloo" },
  { name: "Bullerengue" },
  { name: "Flamenco" },
  { name: "Cantes de ida y vuelta" },
  { name: "Fandangos" },
  { name: "Soleá" },
  { name: "Alegrías" },
  { name: "Bulerías" },
  { name: "Peteneras" },
  { name: "Tango" },
  { name: "Toná" },
  { name: "Martinetes" },
  { name: "Tonás" },
  { name: "Grupera" },
  { name: "Latin Christian" },
  { name: "Latin pop" },
  { name: "Latin ballad" },
  { name: "Latin rock" },
  { name: "Latin alternative" },
  { name: "Rock en Español" },
  { name: "Latin jazz" },
  { name: "Afro-Cuban jazz" },
  { name: "Bossa nova" },
  { name: "Mariachi" },
  { name: "Ranchera" },
  { name: "Reggaeton" },
  { name: "Latin trap" },
  { name: "Banda" },
  { name: "Norteño" },
  { name: "Bachata" },
  { name: "Bolero" },
  { name: "Criolla" },
  { name: "Cumbia" },
  { name: "Chicha" },
  { name: "Porro" },
  { name: "Guajira" },
  { name: "Mambo" },
  { name: "Merengue" },
  { name: "Música popular (Colombia)" },
  { name: "Rumba" },
  { name: "Salsa" },
  { name: "Salsa romántica" },
  { name: "Son" },
  { name: "Tejano" },
  { name: "Timba" },
  { name: "Tropipop" },
  { name: "Urbano music" },
  { name: "Vallenato" },
  { name: "Canadian folk music" },
  { name: "Indigenous music of North America" },
  { name: "Inuit music" },
  { name: "Indigenous music of Canada" },
  { name: "Ragtime" },
  { name: "Cakewalk" },
  { name: "Classic rag" },
  { name: "Folk ragtime" },
  { name: "Honky-tonk piano" },
  { name: "Novelty piano" },
  { name: "Stomp" },
  { name: "Stride piano" },
  { name: "Swing music" },
  { name: "Sikh music" },
  { name: "Buddhist music" },
  { name: "Christian music" },
  { name: "Contemporary Christian music" },
  { name: "Contemporary worship music" },
  { name: "Christian Rock" },
  { name: "Country Gospel" },
  { name: "Church music" },
  { name: "Gospel" },
  { name: "Worship" },
  { name: "Hymns" },
  { name: "Jesus Music" },
  { name: "Liturgical music" },
  { name: "Spirituals" },
  { name: "Gregorian chant" },
  { name: "Islamic music" },
  { name: "Modern pagan music" },
  { name: "New-age music" },
  { name: "Shamanic music" },
  { name: "Traditional folk" },
  { name: "American patriotic music" },
  { name: "Christmas music" },
  { name: "Fado" },
  { name: "Huayno" },
  { name: "Mele" },
  { name: "Pastorale" },
  { name: "Polka" },
  { name: "Ragtime" },
  { name: "Son mexicano" },
  { name: "Música criolla" },
  { name: "Ballroom dance music" },
  { name: "Vogue (dance)" },
  { name: "Children's music" },
  { name: "Dance music" },
  { name: "Slow dance" },
  { name: "Drug use in music" },
  { name: "Incidental music" },
  { name: "Bedroom production" },
  { name: "Multi-instrumentalist" },
  { name: "A cappella" },
  { name: "Bassist" },
  { name: "Drummer" },
  { name: "Percussion" },
  { name: "Found object (music)" },
  { name: "Guitarist" },
  { name: "Pianist" },
  { name: "Keyboardist" },
  { name: "One-man band" },
  { name: "Patriotic music" },
  { name: "Martial industrial" },
  { name: "PC Music" },
  { name: "Hyperpop" },
  { name: "Internet meme" },
  { name: "Virtuoso" },
  { name: "Yodeling" },
];
